# basic
task: "zero_shot"
# save_result: True

# model

# dataset
dataset_name: ActivityNet13
anno_file_path: "./data/ActivityNet13/ActivityNet13_annotations.json"
feature_info_path: "./data/ActivityNet13/CLIP/ActivityNet13_info.json"
description_file_path: "./data/ActivityNet13/ActivityNet13_description_v6.json"
feature_path: "/mnt/Datasets/ActivityNet13/CLIP_feature"
feature_stride: 16
feature_type: "CLIP"
num_classes: 200
split: 75
# split_id: 0
