# basic
task: "zero_shot"
# save_result: True

# model
exp_logit_scale: True
norm_embed: True


# dataset
dataset_name: Thumos14
anno_file_path: "./data/Thumos14/Thumos14_annotations.json"
feature_info_path: "./data/Thumos14/CLIP/Thumos14_info_8frame.json"
description_file_path: "./data/Thumos14/Thumos14_description_v6.json"
feature_path: "/mnt/Datasets/Thumos14/CLIP_feature_8frame"
feature_stride: 8
feature_type: "CLIP"
num_classes: 20
# slice_size: 128
# slice_overlap: 0.75
# inference_slice_overlap: 0.25
split: 75
# split_id: 0